Add files used for cloudrun tutorials
grafeas/voucher2 pull request #2
Opened 2020-10-17 15:37 UTC by ooq

These files added will be used for a tutorial on how to:
- Run Voucher server as a Cloud Run service
- Invoke the voucher server from a Cloud Build pipeline to sign an built image
We need to merge these files before the tutorial is live on `cloud.google.com`.

2020-10-19 14:20 UTC, catherinejones requested changes
A few quick changes to request and some questions!

Could we add a README that points (or can be updated to point in the future!) to the CloudRun tutorial?

2020-10-19 14:20 UTC, catherinejones commented on tutorials/cloudrun/Dockerfile.bad
> +# Debian9 image from Jun 8th, 2020
Would it be possible to move these into a directory called "examples"?

So:

* `tutorials/cloudrun` - everything you need to setup CloudRun
* `tutorials/cloudrun/examples` - examples of how to use the CloudRun setup!

2020-10-19 14:20 UTC, catherinejones commented on tutorials/cloudrun/Dockerfile-server
> +FROM golang:1.13-alpine as builder
Could we bump this to v1.14 or v1.15?

2020-10-19 14:20 UTC, catherinejones commented on tutorials/cloudrun/Dockerfile-server
> +WORKDIR /go/src/github.com/Shopify/voucher
Can this be updated to `github.com/grafeas/voucher` or do we need to update the module path first?

2020-10-19 17:43 UTC, ooq commented on tutorials/cloudrun/Dockerfile.bad
> +# Debian9 image from Jun 8th, 2020
Sounds good! Ack.

2020-10-19 17:43 UTC, ooq commented on tutorials/cloudrun/Dockerfile-server
> +FROM golang:1.13-alpine as builder
Ack.

2020-10-19 17:43 UTC, ooq commented on tutorials/cloudrun/Dockerfile-server
> +WORKDIR /go/src/github.com/Shopify/voucher
I shouldn't matter. I will update it.

2020-10-19 17:45 UTC, ooq commented
Should we add the README in a separate PR? I think the changes should happen in this order:
- merge this PR
- publish the cloudrun google doc
- add README to point to cloudrun doc
I'll create an issue to track the README.

2020-10-23 14:56 UTC, catherinejones approved these changes
Looks good to me! Waiting to add the README after the tutorial goes live sounds reasonable to me!

2020-10-23 15:52 UTC, merged